[2023-03-29 19:30:28,946] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:47:45.028597+00:00 [queued]>
[2023-03-29 19:30:28,958] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:47:45.028597+00:00 [queued]>
[2023-03-29 19:30:28,958] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 19:30:28,959] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2023-03-29 19:30:28,959] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 19:30:28,980] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): merge_task> on 2023-03-29 15:47:45.028597+00:00
[2023-03-29 19:30:28,986] {standard_task_runner.py:52} INFO - Started process 86 to run task
[2023-03-29 19:30:28,989] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_merge_dag', 'merge_task', 'manual__2023-03-29T15:47:45.028597+00:00', '--job-id', '668', '--raw', '--subdir', 'DAGS_FOLDER/data_merge.py', '--cfg-path', '/tmp/tmpdtfc24gt', '--error-file', '/tmp/tmp2yaw66y_']
[2023-03-29 19:30:28,989] {standard_task_runner.py:80} INFO - Job 668: Subtask merge_task
[2023-03-29 19:30:29,097] {task_command.py:369} INFO - Running <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:47:45.028597+00:00 [running]> on host 491e5e6b4ad4
[2023-03-29 19:30:29,227] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kartaca
AIRFLOW_CTX_DAG_ID=data_merge_dag
AIRFLOW_CTX_TASK_ID=merge_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T15:47:45.028597+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T15:47:45.028597+00:00
[2023-03-29 19:30:29,303] {python.py:173} INFO - Done. Returned value was: None
[2023-03-29 19:30:29,325] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_merge_dag, task_id=merge_task, execution_date=20230329T154745, start_date=20230329T193028, end_date=20230329T193029
[2023-03-29 19:30:29,364] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-29 19:30:29,415] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
