[2023-03-29 19:20:15,441] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:47:23.455047+00:00 [queued]>
[2023-03-29 19:20:15,458] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:47:23.455047+00:00 [queued]>
[2023-03-29 19:20:15,458] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 19:20:15,458] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2023-03-29 19:20:15,458] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 19:20:15,479] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): merge_task> on 2023-03-29 15:47:23.455047+00:00
[2023-03-29 19:20:15,487] {standard_task_runner.py:52} INFO - Started process 93 to run task
[2023-03-29 19:20:15,498] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_merge_dag', 'merge_task', 'manual__2023-03-29T15:47:23.455047+00:00', '--job-id', '640', '--raw', '--subdir', 'DAGS_FOLDER/data_merge.py', '--cfg-path', '/tmp/tmps_o1dupp', '--error-file', '/tmp/tmpod9mck6z']
[2023-03-29 19:20:15,499] {standard_task_runner.py:80} INFO - Job 640: Subtask merge_task
[2023-03-29 19:20:15,629] {task_command.py:369} INFO - Running <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:47:23.455047+00:00 [running]> on host 0f918821725a
[2023-03-29 19:20:15,757] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kartaca
AIRFLOW_CTX_DAG_ID=data_merge_dag
AIRFLOW_CTX_TASK_ID=merge_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T15:47:23.455047+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T15:47:23.455047+00:00
[2023-03-29 19:20:15,838] {python.py:173} INFO - Done. Returned value was: None
[2023-03-29 19:20:15,854] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_merge_dag, task_id=merge_task, execution_date=20230329T154723, start_date=20230329T192015, end_date=20230329T192015
[2023-03-29 19:20:15,909] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-29 19:20:15,950] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
