[2023-03-29 15:24:50,881] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:24:48.652075+00:00 [queued]>
[2023-03-29 15:24:50,891] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:24:48.652075+00:00 [queued]>
[2023-03-29 15:24:50,891] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 15:24:50,891] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2023-03-29 15:24:50,891] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 15:24:50,905] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): merge_task> on 2023-03-29 15:24:48.652075+00:00
[2023-03-29 15:24:50,909] {standard_task_runner.py:52} INFO - Started process 85 to run task
[2023-03-29 15:24:50,911] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_merge_dag', 'merge_task', 'manual__2023-03-29T15:24:48.652075+00:00', '--job-id', '420', '--raw', '--subdir', 'DAGS_FOLDER/data_merge.py', '--cfg-path', '/tmp/tmpnw8dw_gh', '--error-file', '/tmp/tmpou_z2_1h']
[2023-03-29 15:24:50,911] {standard_task_runner.py:80} INFO - Job 420: Subtask merge_task
[2023-03-29 15:24:50,958] {task_command.py:369} INFO - Running <TaskInstance: data_merge_dag.merge_task manual__2023-03-29T15:24:48.652075+00:00 [running]> on host 75e36b0b32e7
[2023-03-29 15:24:51,027] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kartaca
AIRFLOW_CTX_DAG_ID=data_merge_dag
AIRFLOW_CTX_TASK_ID=merge_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T15:24:48.652075+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T15:24:48.652075+00:00
[2023-03-29 15:24:51,074] {python.py:173} INFO - Done. Returned value was: None
[2023-03-29 15:24:51,087] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_merge_dag, task_id=merge_task, execution_date=20230329T152448, start_date=20230329T152450, end_date=20230329T152451
[2023-03-29 15:24:51,124] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-29 15:24:51,158] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
